version: '3.9'

services:
  app:
    image: scrapyrealestate/mferark
    container_name: scrapyrealestate
    volumes:
      # - %USERPROFILE%
      - ~/Dropbox/code/docker/utils/scrapyrealestate/:/scrapyrealestate/

    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t

volumes:
  ansible: {}